Repository SRombauts/SQLiteCpp, pull requests merged in 2022-12, with the labels that each got.

#387 Ensure that TEXT column is UTF-8 encoded before using sqlite3_column_blob()
  src/Column.cpp
  tests/Column_test.cpp
Labels: bug

#385 Fix #382 #74 disable SQLITECPP_USE_STACK_PROTECTION when on MinGW
  CMakeLists.txt
Labels: enhancement

#388 make std::filesystem optional
  CMakeLists.txt
  include/SQLiteCpp/Database.h
  meson.build
  meson_options.txt
Labels: enhancement

#393 Fix preprocessor issues
  include/SQLiteCpp/Database.h
  tests/Database_test.cpp
Labels: bug

#394 check if SQLITE_OPEN_NOFOLLOW is defined
  src/Database.cpp
Labels: bug

#391 meson project changes based on wrap submission review
  meson.build
  meson_options.txt
Labels: enhancement

#390 fix incorrect work of savepoint
  src/Database.cpp
  src/Savepoint.cpp
  tests/Savepoint_test.cpp
Labels: bug

#396 Rename Savepoint RollbackTo() and fix class comments and formatting
  include/SQLiteCpp/Savepoint.h
  src/Savepoint.cpp
Labels: bug, enhancement

#384 Add Mingw GitHub actions
  .github/workflows/build.yml
Labels: enhancement

#397 Add a Transaction::rollback() method
  include/SQLiteCpp/Transaction.h
  src/Transaction.cpp
  tests/Transaction_test.cpp
Labels: enhancement

#395 add meson usage guide
  README.md
  examples/example1/meson.build
  examples/example2/meson.build
  examples/meson.build
  meson.build
  subprojects/sqlitecpp.wrap
Labels: enhancement

#400 Lint corrections
  CMakeLists.txt
  meson.build
Labels: bug, enhancement
