Repository SRombauts/SQLiteCpp, pull requests merged in 2023-08, with the labels that each got.

#434 Define SQLITECPP_COMPILE_DLL as PUBLIC
  CMakeLists.txt
Labels: bug

#438 Update usage of SQLITECPP_USE_STATIC_RUNTIME
  CMakeLists.txt
Labels: enhancement

#440 Declare BUILD_SHARED_LIBS option for discoverability
  CMakeLists.txt
  sqlite3/CMakeLists.txt
Labels: enhancement

#442 Set -DBUILD_SHARED_LIBS=ON by default on scripts and CI/CD
  .github/workflows/build.yml
  CMakeLists.txt
  build.bat
  build.sh
Labels: enhancement

#444 Rename the original build.yml to cmake.yml vs meson.yml
  .github/workflows/cmake.yml
  .github/workflows/cmake_subdir_example.yml
  .github/workflows/meson.yml
  CMakeLists.txt
Labels: enhancement

#450 Fix and update Travis CI workflow
  .travis.yml
  include/SQLiteCpp/Statement.h
  tests/Column_test.cpp
  tests/Statement_test.cpp
Labels: bug, enhancement
