Repository SRombauts/SQLiteCpp, pull requests merged in 2024-08, with the labels that each got.

#476 Macos ci fix
  .github/workflows/meson.yml
Labels: bug

#475 Update meson dependencies [Meson only]
  examples/example1/meson.build
  examples/example2/meson.build
  meson.build
  subprojects/gtest.wrap
  subprojects/sqlite3.wrap
Labels: update

#469 Explicitly =delete; Statement::bindNoCopy(..., std::string&&)
  include/SQLiteCpp/Statement.h
Labels: enhancement

#479 Release 3.3.2
  CHANGELOG.md
  CMakeLists.txt
  Doxyfile
  LICENSE.txt
  README.md
  appveyor.yml
  build.bat
  build.sh
  examples/example1/main.cpp
  include/SQLiteCpp/Assertion.h
  include/SQLiteCpp/Backup.h
  include/SQLiteCpp/Column.h
  include/SQLiteCpp/Database.h
  include/SQLiteCpp/Exception.h
  include/SQLiteCpp/ExecuteMany.h
  include/SQLiteCpp/SQLiteCpp.h
  include/SQLiteCpp/Savepoint.h
  include/SQLiteCpp/Statement.h
  include/SQLiteCpp/Transaction.h
  include/SQLiteCpp/VariadicBind.h
  meson.build
  package.xml
  sqlite3/CMakeLists.txt
  src/Backup.cpp
  src/Column.cpp
  src/Database.cpp
  src/Exception.cpp
  src/Savepoint.cpp
  src/Statement.cpp
  src/Transaction.cpp
  tests/Column_test.cpp
  tests/Database_test.cpp
Labels: update

#480 Add a Github Dependabot config file
  .github/dependabot.yml
  CMakeLists.txt
Labels: enhancement

#483 Replace all double-quoted string literals by single quotes in unit test
  CMakeLists.txt
  examples/example1/main.cpp
  tests/Backup_test.cpp
  tests/Column_test.cpp
  tests/Database_test.cpp
  tests/Statement_test.cpp
  tests/Transaction_test.cpp
Labels: bug

#484 Use explicit versions of Ubuntu images instead of latest
  .github/workflows/cmake.yml
Labels: ci

#454 Add logic to use different FindPackage for python if cmake is above 3.12
  CMakeLists.txt
Labels: enhancement
